### ISSUE TITLE
IndexError when training the model with modified dataset

### ISSUE THREAD

**Issue by rexarski** [amandakonet/climate-change-misinformation#1]
Hi, @amandakonet. I wonder if you still remember some details when you fine-tune the model with your modified version of `climate_fever`.

Basically I was following your notebook and everything was fine until the last step in `1-climate-bert.ipynb`, where an `IndexError: index out of range in self` was raised when I actually tried to train the model `train(model, train_loader, val_loader, optimizer)`.

I wonder if you've encountered a similar roadblocker like that and how you get past it. Thanks!

**Comment by amandakonet** [comment]
Hi @rexarski, 

At the time of writing this, I didn't encounter any such issue. It's possible that this issue is due to changes to the transformers library. Unfortunately, I don't have capacity to address this right now. However, if you (or anyone else) figures this out, I'd be more than happy to merge in a pull request!

**Comment by rexarski** [comment]
Thanks @amandakonet, I'll keep you updated if I've made some progress. Cheers!
